import { Waveform, InstrumentPreset } from "../types";

export const PRESETS: InstrumentPreset[] = [
  {
    name: 'Shred Lead Pro',
    waveform: Waveform.GUITAR,
    filterCutoff: 4500,
    resonance: 8,
    attack: 0.01,
    decay: 0.2,
    sustain: 0.6,
    release: 0.4,
    detune: 5,
    vibratoRate: 6,
    vibratoDepth: 0.15,
    distortion: 0.8,
    delayFeedback: 0.4,
    delayTime: 0.3,
    reverbWet: 0.3,
    feedbackAmount: 0.2,
    stringDamping: 0.3
  },
  {
    name: 'Concert Grand',
    waveform: Waveform.PIANO,
    filterCutoff: 3000,
    resonance: 2,
    attack: 0.005,
    decay: 0.8,
    sustain: 0.3,
    release: 1.2,
    detune: 0,
    vibratoRate: 0,
    vibratoDepth: 0,
    distortion: 0,
    delayFeedback: 0.1,
    delayTime: 0.2,
    reverbWet: 0.4,
    feedbackAmount: 0,
    stringDamping: 0.5
  },
  {
    name: 'Delta Slide',
    waveform: Waveform.SLIDE,
    filterCutoff: 5000,
    resonance: 4,
    attack: 0.05,
    decay: 0.3,
    sustain: 0.8,
    release: 0.6,
    detune: 2,
    vibratoRate: 5,
    vibratoDepth: 0.2,
    distortion: 0.4,
    delayFeedback: 0.3,
    delayTime: 0.25,
    reverbWet: 0.2,
    feedbackAmount: 0.1,
    stringDamping: 0.2
  },
  {
    name: 'Studio Kit',
    waveform: Waveform.DRUMS,
    filterCutoff: 8000,
    resonance: 1,
    attack: 0.001,
    decay: 0.2,
    sustain: 0,
    release: 0.1,
    detune: 0,
    vibratoRate: 0,
    vibratoDepth: 0,
    distortion: 0.2,
    delayFeedback: 0,
    delayTime: 0,
    reverbWet: 0.1,
    feedbackAmount: 0,
    stringDamping: 0.8
  },
  {
    name: 'Neon Pulse',
    waveform: Waveform.SAWTOOTH,
    filterCutoff: 2000,
    resonance: 12,
    attack: 0.02,
    decay: 0.4,
    sustain: 0.5,
    release: 0.8,
    detune: 10,
    vibratoRate: 4,
    vibratoDepth: 0.1,
    distortion: 0.3,
    delayFeedback: 0.6,
    delayTime: 0.4,
    reverbWet: 0.5,
    feedbackAmount: 0,
    stringDamping: 0
  },
  {
    name: 'Clean Strat',
    waveform: Waveform.PHYSICAL_STRING,
    filterCutoff: 6000,
    resonance: 3,
    attack: 0.01,
    decay: 0.5,
    sustain: 0.4,
    release: 0.8,
    detune: 0,
    vibratoRate: 5,
    vibratoDepth: 0.05,
    distortion: 0.1,
    delayFeedback: 0.2,
    delayTime: 0.3,
    reverbWet: 0.2,
    feedbackAmount: 0.05,
    stringDamping: 0.4
  },
  {
    name: 'Sub Bass 808',
    waveform: Waveform.SINE,
    filterCutoff: 400,
    resonance: 1,
    attack: 0.01,
    decay: 1.2,
    sustain: 0.1,
    release: 0.5,
    detune: 0,
    vibratoRate: 0,
    vibratoDepth: 0,
    distortion: 0.3,
    delayFeedback: 0,
    delayTime: 0,
    reverbWet: 0,
    feedbackAmount: 0,
    stringDamping: 0
  },
  {
    name: 'Space Flute',
    waveform: Waveform.TRIANGLE,
    filterCutoff: 1500,
    resonance: 5,
    attack: 0.2,
    decay: 0.3,
    sustain: 0.8,
    release: 1.5,
    detune: 5,
    vibratoRate: 7,
    vibratoDepth: 0.3,
    distortion: 0.05,
    delayFeedback: 0.5,
    delayTime: 0.6,
    reverbWet: 0.6,
    feedbackAmount: 0,
    stringDamping: 0
  },
  {
    name: 'Heavy Bit',
    waveform: Waveform.SQUARE,
    filterCutoff: 3500,
    resonance: 15,
    attack: 0.005,
    decay: 0.1,
    sustain: 0.7,
    release: 0.3,
    detune: 0,
    vibratoRate: 0,
    vibratoDepth: 0,
    distortion: 0.9,
    delayFeedback: 0.3,
    delayTime: 0.1,
    reverbWet: 0.1,
    feedbackAmount: 0,
    stringDamping: 0
  },
  {
    name: 'Steel String',
    waveform: Waveform.GUITAR,
    filterCutoff: 7000,
    resonance: 2,
    attack: 0.01,
    decay: 0.8,
    sustain: 0.2,
    release: 1.0,
    detune: 0,
    vibratoRate: 0,
    vibratoDepth: 0,
    distortion: 0,
    delayFeedback: 0.1,
    delayTime: 0.2,
    reverbWet: 0.2,
    feedbackAmount: 0,
    stringDamping: 0.2
  },
  {
    name: 'Ethereal Pad',
    waveform: Waveform.SAWTOOTH,
    filterCutoff: 1200,
    resonance: 4,
    attack: 2.5,
    decay: 1.0,
    sustain: 0.9,
    release: 3.0,
    detune: 15,
    vibratoRate: 2,
    vibratoDepth: 0.1,
    distortion: 0,
    delayFeedback: 0.7,
    delayTime: 0.5,
    reverbWet: 0.8,
    feedbackAmount: 0,
    stringDamping: 0
  },
  {
    name: 'Slap Bass',
    waveform: Waveform.PHYSICAL_STRING,
    filterCutoff: 2500,
    resonance: 6,
    attack: 0.005,
    decay: 0.3,
    sustain: 0.2,
    release: 0.4,
    detune: 0,
    vibratoRate: 0,
    vibratoDepth: 0,
    distortion: 0.3,
    delayFeedback: 0.1,
    delayTime: 0.15,
    reverbWet: 0.1,
    feedbackAmount: 0.2,
    stringDamping: 0.6
  },
  {
    name: 'Vibraphone',
    waveform: Waveform.SINE,
    filterCutoff: 2000,
    resonance: 1,
    attack: 0.005,
    decay: 1.5,
    sustain: 0.1,
    release: 1.0,
    detune: 2,
    vibratoRate: 6,
    vibratoDepth: 0.4,
    distortion: 0,
    delayFeedback: 0.2,
    delayTime: 0.4,
    reverbWet: 0.5,
    feedbackAmount: 0,
    stringDamping: 0
  },
  {
    name: 'Square Lead',
    waveform: Waveform.SQUARE,
    filterCutoff: 4000,
    resonance: 4,
    attack: 0.01,
    decay: 0.2,
    sustain: 0.8,
    release: 0.5,
    detune: 8,
    vibratoRate: 5,
    vibratoDepth: 0.15,
    distortion: 0.4,
    delayFeedback: 0.4,
    delayTime: 0.2,
    reverbWet: 0.2,
    feedbackAmount: 0,
    stringDamping: 0
  },
  {
    name: 'Dampened Pluck',
    waveform: Waveform.PHYSICAL_STRING,
    filterCutoff: 800,
    resonance: 2,
    attack: 0.01,
    decay: 0.2,
    sustain: 0,
    release: 0.2,
    detune: 0,
    vibratoRate: 0,
    vibratoDepth: 0,
    distortion: 0,
    delayFeedback: 0.5,
    delayTime: 0.2,
    reverbWet: 0.3,
    feedbackAmount: 0,
    stringDamping: 0.95
  }
];

export const generateAIPreset = async (mood: string): Promise<InstrumentPreset> => {
  // This function is now a proxy for picking a preset from the 15
  await new Promise(resolve => setTimeout(resolve, 200));
  const found = PRESETS.find(p => p.name.toLowerCase().includes(mood.toLowerCase()));
  return found || PRESETS[0];
};
